name: Build Docker Server

on:
  workflow_dispatch:
    inputs:
      server_name:
        description: 'Name of the Docker container'
        required: true
        default: 'nginx-server'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install Docker (official script)
        run: |
          curl -fsSL https://get.docker.com -o get-docker.sh
          sh get-docker.sh

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve -var="server_name=${{ github.event.inputs.server_name }}"

      - name: Output container info
        run: terraform output
